### ISSUE TITLE
Wont let players do the transactions

### ISSUE THREAD

**Issue by hinoraito** [WizarTheGreat/DiamondShop#6]
When setting up shops, the players can't buy the items even if they are holding the correct amount of diamonds.
The item sold is in the correct amount in the chest.
There are no syntax error on the sign.
When you click on the chest with diamonds there are no messages in the chat but there is a message on the console from the plugin that just states the item that is sold by the shop.

We are running 1.21 paper server.

**Comment by WizarTheGreat** [comment]
Could you send a picture/video of the sign and inside of the chest?

**Comment by hinoraito** [comment]
Thanks for your speedy reply!
Here are some screenshots of the sign and chest. I noticed that the transactions will only work if I set up a shop myself(maybe it has to do with the fact I'm op?). My players shops wont work at all and say they are just out of stock no matter what. Also, if I put the wrong amount of items in a stack in the chest, the transaction wont happen. In this example I sold 1 netherrack and if my stack had more than one, it wouldn't recognize it.

![2024-09-06_11 58 44](https://github.com/user-attachments/assets/07319a26-0f33-4aaa-aa63-0015b6d61376)
![2024-09-06_11 58 48](https://github.com/user-attachments/assets/5747c041-da10-412c-b53e-ec4ab98b039c)
![2024-09-06_11 58 56](https://github.com/user-attachments/assets/0604da68-4606-4f8a-be71-d1f8db0052c7)

**Comment by WizarTheGreat** [comment]
Are you using some sort of nick plugin?
And it will only take from a slot, as i tried to imitate how you would fill a chest in something like hermitcraft to keep it as vanilla as possible

**Comment by hinoraito** [comment]
No nick plugin. All I have is ranks showing in front of the player names.

**Comment by WizarTheGreat** [comment]
Ah I see, I've changed it to work with the UUID instead of the name in v1.2.1

**Comment by hinoraito** [comment]
It seems to work so far! Thanks for the fix. Will you update the spigot download if anyone wants to download the updated plugin?

**Comment by WizarTheGreat** [comment]
I update the spigot and github together, so yes
