### ISSUE TITLE
Items sold disappear when buyer's inventory is full prior to making the transaction

### ISSUE THREAD

**Issue by hinoraito** [WizarTheGreat/DiamondShop#8]
If a buyer tries to make a purchase but their inventory is full, the item they bought will disappear from the chest shop and will be lost.
![2024-09-18_14 32 08](https://github.com/user-attachments/assets/31dbbadd-bc17-4fa7-a0f2-b3472be7a832)
![2024-09-18_14 32 13](https://github.com/user-attachments/assets/6e8cad32-4327-4d36-85a3-00aae79248ce)
![2024-09-18_14 32 37](https://github.com/user-attachments/assets/ec4f4c12-048f-4d82-8718-d36dcdf6dc66)

**Comment by WizarTheGreat** [comment]
This is fixed in ver 1.3.0
Thank you for making me aware of this!
